### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by alphamarket** [jasondew/fastout#1]
it would be nice if any documentation provided!

**Comment by jasondew** [comment]
Hi there! There is inline documentation in the [main Ruby file](https://github.com/jasondew/fastout/blob/master/lib/fastout/ranker.rb) as well as [specs](https://github.com/jasondew/fastout/blob/master/spec/fastout/ranker_spec.rb). There's also [the paper that describes the algorithm](https://pdfs.semanticscholar.org/8569/7a2277d47fa155b135144aa897dc76eeb562.pdf) if you're more interested in the theoretical backing.
